cmake_minimum_required(VERSION 3.16)
project(Vortex LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
add_subdirectory(shared)
add_subdirectory(core-scanner)
add_subdirectory(driver-check)
add_executable(vortex-backend main.cpp)
target_compile_definitions(vortex-backend PRIVATE "BUILD_VORTEX_BACKEND")
target_include_directories(vortex-backend PRIVATE ${CMAKE_SOURCE_DIR})
target_link_libraries(vortex-backend PRIVATE vortex-scanner vortex-driver-check vortex-shared)
if (WIN32)
    target_compile_definitions(vortex-backend PRIVATE PLATFORM_WINDOWS)
    target_link_libraries(vortex-backend PRIVATE Advapi32 User32 Gdi32 Psapi)
endif()
